/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class PjsuaAppCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PjsuaAppCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PjsuaAppCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_PjsuaAppCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pjsuaJNI.PjsuaAppCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pjsuaJNI.PjsuaAppCallback_change_ownership(this, swigCPtr, true);
  }

  public void onStarted(String msg) {
    if (getClass() == PjsuaAppCallback.class) pjsuaJNI.PjsuaAppCallback_onStarted(swigCPtr, this, msg); else pjsuaJNI.PjsuaAppCallback_onStartedSwigExplicitPjsuaAppCallback(swigCPtr, this, msg);
  }

  public void onStopped(int restart) {
    if (getClass() == PjsuaAppCallback.class) pjsuaJNI.PjsuaAppCallback_onStopped(swigCPtr, this, restart); else pjsuaJNI.PjsuaAppCallback_onStoppedSwigExplicitPjsuaAppCallback(swigCPtr, this, restart);
  }

  public PjsuaAppCallback() {
    this(pjsuaJNI.new_PjsuaAppCallback(), true);
    pjsuaJNI.PjsuaAppCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
