/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsua {
  public static int pjsuaStart() {
    return pjsuaJNI.pjsuaStart();
  }

  public static void pjsuaDestroy() {
    pjsuaJNI.pjsuaDestroy();
  }

  public static int pjsuaRestart() {
    return pjsuaJNI.pjsuaRestart();
  }

  public static void setCallbackObject(PjsuaAppCallback callback) {
    pjsuaJNI.setCallbackObject(PjsuaAppCallback.getCPtr(callback), callback);
  }

}
