/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsuaJNI {
  public final static native int pjsuaStart();
  public final static native void pjsuaDestroy();
  public final static native int pjsuaRestart();
  public final static native void delete_PjsuaAppCallback(long jarg1);
  public final static native void PjsuaAppCallback_onStarted(long jarg1, PjsuaAppCallback jarg1_, String jarg2);
  public final static native void PjsuaAppCallback_onStartedSwigExplicitPjsuaAppCallback(long jarg1, PjsuaAppCallback jarg1_, String jarg2);
  public final static native void PjsuaAppCallback_onStopped(long jarg1, PjsuaAppCallback jarg1_, int jarg2);
  public final static native void PjsuaAppCallback_onStoppedSwigExplicitPjsuaAppCallback(long jarg1, PjsuaAppCallback jarg1_, int jarg2);
  public final static native long new_PjsuaAppCallback();
  public final static native void PjsuaAppCallback_director_connect(PjsuaAppCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void PjsuaAppCallback_change_ownership(PjsuaAppCallback obj, long cptr, boolean take_or_release);
  public final static native void setCallbackObject(long jarg1, PjsuaAppCallback jarg1_);

  public static void SwigDirector_PjsuaAppCallback_onStarted(PjsuaAppCallback self, String msg) {
    self.onStarted(msg);
  }
  public static void SwigDirector_PjsuaAppCallback_onStopped(PjsuaAppCallback self, int restart) {
    self.onStopped(restart);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
